"""add snapshot model

Revision ID: 0ace7aaab142
Revises: bfb252820654
Create Date: 2025-07-21 12:28:40.924050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ace7aaab142'
down_revision: Union[str, Sequence[str], None] = 'bfb252820654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('snapshot_id', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('value', sa.Float(), nullable=False))
    op.add_column('metrics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_metrics_name'), table_name='metrics')
    op.create_index(op.f('ix_metrics_name'), 'metrics', ['name'], unique=False)
    op.create_foreign_key(None, 'metrics', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    op.add_column('snapshots', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('snapshots_host_id_fkey'), 'snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'snapshots', 'hosts', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_column('snapshots', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('snapshots_host_id_fkey'), 'snapshots', 'hosts', ['host_id'], ['id'])
    op.drop_column('snapshots', 'created_at')
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_index(op.f('ix_metrics_name'), table_name='metrics')
    op.create_index(op.f('ix_metrics_name'), 'metrics', ['name'], unique=True)
    op.drop_column('metrics', 'created_at')
    op.drop_column('metrics', 'value')
    op.drop_column('metrics', 'snapshot_id')
    # ### end Alembic commands ###
