"""Add host_id to alerts table

Revision ID: 247877720273
Revises: de042ced04db
Create Date: 2025-10-17 13:30:03.183386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '247877720273'
down_revision: Union[str, Sequence[str], None] = 'de042ced04db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'hosts', ['host_id'], ['id'])
    op.alter_column('metrics', 'host_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('metrics', 'host_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'host_id')
    # ### end Alembic commands ###
