"""add acknowledged to alerts

Revision ID: a329d241b715
Revises: 0ace7aaab142
Create Date: 2025-07-21 14:53:59.910706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a329d241b715'
down_revision: Union[str, Sequence[str], None] = '0ace7aaab142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('type', sa.String(), nullable=False))
    op.alter_column('alerts', 'snapshot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('alerts_snapshot_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_snapshot_id_fkey'), 'alerts', 'snapshots', ['snapshot_id'], ['id'])
    op.alter_column('alerts', 'snapshot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('alerts', 'type')
    # ### end Alembic commands ###
